// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0FskJQr2xvDWH6jbJIP_zsKceT_oHG0',
    appId: '1:548351194654:web:806c61208b917a633ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    authDomain: 'event-9da2e.firebaseapp.com',
    storageBucket: 'event-9da2e.firebasestorage.app',
    measurementId: 'G-DX26E32XN8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEcgiJvrZMJEf6A9BHHgAndhRygr-PcI',
    appId: '1:548351194654:ios:f1611eb36a81056a3ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    storageBucket: 'event-9da2e.firebasestorage.app',
    androidClientId: '548351194654-q1an29l5ddn2uhk3dqjo9v3nvst9tq5r.apps.googleusercontent.com',
    iosClientId: '548351194654-f3pkk984o6udfcg9rc14k0tkq2jof7kc.apps.googleusercontent.com',
    iosBundleId: 'com.peersglobal.conclave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEcgiJvrZMJEf6A9BHHgAndhRygr-PcI',
    appId: '1:548351194654:ios:8e8c64c1eebe7e853ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    storageBucket: 'event-9da2e.firebasestorage.app',
    iosClientId: '548351194654-9hp5k1pbn7ceg89d9800o0vas87ev2gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.peersglobleeventapp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt0FskJQr2xvDWH6jbJIP_zsKceT_oHG0',
    appId: '1:548351194654:web:22cdf34959a45f863ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    authDomain: 'event-9da2e.firebaseapp.com',
    storageBucket: 'event-9da2e.firebasestorage.app',
    measurementId: 'G-P0Z13DB66H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4YmrfV34kNF2p7PF_ubkk5mA71L5k-3M',
    appId: '1:548351194654:android:dba8378e8fc5bc6c3ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    storageBucket: 'event-9da2e.firebasestorage.app',
  );

}