// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0FskJQr2xvDWH6jbJIP_zsKceT_oHG0',
    appId: '1:548351194654:web:af323a0a994c53863ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    authDomain: 'event-9da2e.firebaseapp.com',
    storageBucket: 'event-9da2e.firebasestorage.app',
    measurementId: 'G-4QDM0VDZHG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEcgiJvrZMJEf6A9BHHgAndhRygr-PcI',
    appId: '1:548351194654:ios:1a1abc5888683eb33ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    storageBucket: 'event-9da2e.firebasestorage.app',
    iosClientId: '548351194654-c50qnj13lm09c4gsmn92p1o57uv47ctl.apps.googleusercontent.com',
    iosBundleId: 'com.example.peersglobleeventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEcgiJvrZMJEf6A9BHHgAndhRygr-PcI',
    appId: '1:548351194654:ios:8e8c64c1eebe7e853ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    storageBucket: 'event-9da2e.firebasestorage.app',
    iosClientId: '548351194654-9hp5k1pbn7ceg89d9800o0vas87ev2gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.peersglobleeventapp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt0FskJQr2xvDWH6jbJIP_zsKceT_oHG0',
    appId: '1:548351194654:web:0d46ff977f7986ad3ba00f',
    messagingSenderId: '548351194654',
    projectId: 'event-9da2e',
    authDomain: 'event-9da2e.firebaseapp.com',
    storageBucket: 'event-9da2e.firebasestorage.app',
    measurementId: 'G-YQVXBM3JDB',
  );
}
